version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=ravi
      - MONGO_URI=mongodb+srv://user:kush123@cluster0.4xk9u.mongodb.net/ecomravi?retryWrites=true&w=majority
    ports:
      - '3000:3000'
